name: Kevin Samuel
desc:
  en: >
    I work with languages human and computer
  fr: >
    Je travaille en langages humains et informatiques
langs:
  en:
    name: English
    flag: 🇬🇧
  fr:
    name: Français
    flag: 🇫🇷
